export const colorMap = {
0: {color:'blueviolet'},
1: {color:'red'},
2: {color:'yellow'},
3: {color:'lime'},
4: {color:'blue'},
5: {color:'green'},
6: {color:'fuchsia'},
7: {color:'purple'},
8: {color:'aqua'},
9: {color:'deeppink'},
10:{color:'dodgerblue'},
11:{color:'indianred'},
12:{color:'mediumvioletred'},
}